package fr.erm.sae201.controleur.auth;

import fr.erm.sae201.metier.service.AuthService;
import fr.erm.sae201.utils.NotificationUtils;
import fr.erm.sae201.vue.MainApp;
import fr.erm.sae201.vue.auth.ForgotPasswordView;

/**
 * Controller for the "Forgot Password" view.
 * This class manages the user interactions and logic for the password recovery process,
 * including sending a reset code and validating it.
 *
 * @author Ewan QUELO, Raphael MILLE, Matheo BIET
 * @version 1.0
 */
public class ForgotPasswordController {

    
    private final ForgotPasswordView view;
    private final MainApp navigator;
    private final AuthService authService;

    /**
     * The verification code generated by the {@link AuthService} and sent to the user's email.
     * This code is used to verify the user's identity before allowing a password reset.
     */
    private String generatedCode;


    /**
     * Constructs a new ForgotPasswordController
     *
     * @param view The {@link ForgotPasswordView} instance this controller manages
     * @param navigator The {@link MainApp} instance used for navigation between views
     * @param authService The {@link AuthService} instance for handling authentication logic,
     *                    such as sending reset codes.
     */
    public ForgotPasswordController(ForgotPasswordView view, MainApp navigator, AuthService authService) {
        this.authService = authService;
        this.view = view;
        this.navigator = navigator;
        initializeListeners();
    }

    /**
     * Initializes event listeners for the UI components in the {@link ForgotPasswordView}
     * It sets up actions for the send code/validate code button and the back-to-login link
     */
    private void initializeListeners() {
        view.getSendCodeButton().setOnAction(e -> handleSendCode());
        // ADDED: Listener for the new back-to-login link
        view.getLoginLink().setOnAction(e -> handleNavigateToLogin());
    }

    /**
     * Handles the action of sending a password reset code to the user's email
     * It validates the email format, then uses the {@link AuthService} to send the code.
     * If successful, it updates the UI to allow code input and changes the button's action
     * to validate the entered code. Displays appropriate notifications for success or failure.
     */
    private void handleSendCode() {
        String email = view.getEmail();
        System.out.println("CONTROLLER: Requesting code for email: " + email);

        if (email.isEmpty() || !email.contains("@")) {
            NotificationUtils.showWarning("Email invalide", "Veuillez saisir un email valide.");
            return;
        }

        try {
            this.generatedCode = authService.sendResetCode(email);

            if (this.generatedCode != null) {
                NotificationUtils.showSuccess("Code envoyé", "Un code a été envoyé à votre adresse email.");
                System.out.println("INFO: Code input field is now visible.");
                view.showCodeField();
                
                view.getSendCodeButton().setText("Valider le code");
                view.getSendCodeButton().setOnAction(e -> handleValidateCode());
            } else {
                 NotificationUtils.showError("Erreur", "Le code n'a pas pu être envoyé.");
            }
        } catch (Exception ex) {
            System.err.println("ERROR sending email: " + ex.getMessage());
            NotificationUtils.showError("Erreur d'envoi", "Impossible d'envoyer l'email. Vérifiez votre configuration ou contactez un administrateur.");
        }
    }
    
    /**
     * Handles the action of validating the reset code entered by the user.
     * It compares the code entered in the view with the 'generatedCode' stored internally.
     * If the code is valid, it navigates the user to the password reset screen.
     * Otherwise, it displays an error notification.
     */
    private void handleValidateCode() {
        String email = view.getEmail();
        String codeFromUser = view.getCode();
        System.out.println("CONTROLLER: Validating code '" + codeFromUser + "' for email " + email);
        
        boolean isCodeValid = generatedCode != null && generatedCode.equals(codeFromUser);

        if (isCodeValid) {
            System.out.println("SUCCESS: Code is valid. Navigating to password reset.");
            navigator.showResetPasswordScreen(email); 
        } else {
            System.out.println("ERROR: Invalid code.");
            NotificationUtils.showError("Code incorrect", "Le code que vous avez saisi est incorrect.");
        }
    }

    /**
     * Handles navigation back to the login screen.
     */
    private void handleNavigateToLogin() {
        System.out.println("CONTROLLER: Navigating back to login screen.");
        navigator.showLoginScreen();
    }
}